name: synpar
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - pytorch=1.12.1
  - torchvision=0.13.1
  - numpy=1.23.1
  - pillow=9.2.0
  - pip
  - pip:
    - dlib==19.24.0
    - easydict 
    - click 
    - pyyaml 
    - scipy 
    - ninja 
    - huggingface_hub 
